### ISSUE TITLE
Unable to resolve module ./index

### ISSUE THREAD

**Issue by nrowley** [t3-oss/create-t3-turbo#31]
Hey guys, love what you've done with this monorepo setup and the t3 stack :)

I've been running into this issue on my project:
![Screenshot 2022-10-11 at 14 45 03](https://user-images.githubusercontent.com/47508642/195108308-0e8e334f-5645-4f03-bfc1-84f61172a743.png)

this happens when i try to run the bundled ios app using `npx expo run:ios` as well `expo run:ios`

this is happening on a clean clone of the repo as well as my personal project repo :(

would love if you could point me in the right direction.

**Comment by nrowley** [comment]
I need to run it using expo run:ios as I am using a datepicker library that has native code which will not work on expo go

**Comment by nrowley** [comment]
i think its similar to this issue https://github.com/expo/expo-cli/issues/4509

**Comment by juliusmarminge** [comment]
Maybe @byCedric has some idea?

**Comment by nrowley** [comment]
please let me know if you need more info

**Comment by nrowley** [comment]
just to confirm i cloned the branch again and ran the steps in the repo README

1. pnpm i
2. changed the db provider in schema.prisma to `sqlite`
3.echo DATABASE_URL=file:./db.sqlite >> packages/db/.env
4. pnpm db-push
5. cd /apps/expo
6. npx expo run:ios


i get the following error
```bash
 Config synced
✔ Installed pods and initialized Xcode workspace.
› Planning build
› Compiling react-native Pods/DoubleConversion » bignum.cc
› Compiling react-native Pods/DoubleConversion » strtod.cc
› Compiling react-native Pods/DoubleConversion » fast-dtoa.cc
› Compiling react-native Pods/DoubleConversion » fixed-dtoa.cc
› Compiling react-native Pods/DoubleConversion » double-conversion.cc
› Compiling react-native Pods/DoubleConversion » diy-fp.cc
› Compiling react-native Pods/DoubleConversion » cached-powers.cc
› Compiling react-native Pods/DoubleConversion » bignum-dtoa.cc
› Compiling react-native Pods/DoubleConversion » DoubleConversion-dummy.m
› Packaging react-native Pods/DoubleConversion » libDoubleConversion.a
› Compiling react-native Pods/glog » demangle.cc
› Compiling react-native Pods/fmt » fmt-dummy.m
› Compiling react-native Pods/RCT-Folly » Assume.cpp
› Compiling react-native Pods/Yoga » event.cpp
› Compiling react-native Pods/React-jsinspector » InspectorInterfaces.cpp
› Compiling react-native Pods/React-perflogger » BridgeNativeModulePerfLogger.cpp
› Compiling react-native Pods/React-logger » React-logger-dummy.m
› Compiling react-native Pods/React-jsi » JSCRuntime.cpp
› Compiling react-native Pods/React-cxxreact » CxxNativeModule.cpp
› Compiling react-native Pods/React-bridging » LongLivedObject.cpp
› Compiling react-native Pods/React-jsiexecutor » JSIExecutor.cpp
› Compiling react-native Pods/React-Core » JSCExecutorFactory.mm
› Compiling react-native Pods/ReactCommon » RCTBlockGuard.mm
› Compiling react-native Pods/React-logger » react_native_log.cpp
› Compiling react-native Pods/React-RCTText » NSTextStorage+FontScaling.m
› Compiling react-native Pods/fmt » format.cc
› Compiling @shopify/flash-list Pods/RNFlashList » AutoLayoutViewManager.swift
› Compiling @shopify/flash-list Pods/RNFlashList » CellContainerManager.swift
› Compiling @shopify/flash-list Pods/RNFlashList » CellContainer.swift
› Compiling @shopify/flash-list Pods/RNFlashList » AutoLayoutView.swift
› Compiling react-native Pods/React-perflogger » React-perflogger-dummy.m
› Compiling react-native Pods/Yoga » log.cpp
› Compiling react-native Pods/Yoga » experiments.cpp
› Compiling react-native Pods/Yoga » Yoga.cpp
› Compiling react-native Pods/glog » vlog_is_on.cc
› Compiling react-native Pods/glog » utilities.cc
› Compiling react-native Pods/glog » symbolize.cc
› Compiling react-native Pods/glog » signalhandler.cc
› Compiling react-native Pods/glog » raw_logging.cc
› Compiling react-native Pods/glog » logging.cc
› Compiling react-native Pods/glog » glog-dummy.m
› Compiling react-native Pods/Yoga » Yoga-dummy.m
› Compiling react-native Pods/Yoga » YGValue.cpp
› Compiling react-native Pods/Yoga » YGStyle.cpp
› Compiling react-native Pods/Yoga » YGNodePrint.cpp
› Compiling react-native Pods/Yoga » YGNode.cpp
› Compiling react-native Pods/Yoga » YGLayout.cpp
› Compiling react-native Pods/Yoga » YGEnums.cpp
› Compiling react-native Pods/Yoga » YGConfig.cpp
› Compiling react-native Pods/Yoga » Utils.cpp
› Compiling react-native Pods/React-RCTText » React-RCTText-dummy.m
› Compiling react-native Pods/ReactCommon » TurboModuleUtils.cpp
› Compiling react-native Pods/ReactCommon » TurboModulePerfLogger.cpp
› Packaging react-native Pods/fmt » libfmt.a
› Compiling react-native Pods/ReactCommon » TurboModuleBinding.cpp
› Compiling react-native Pods/ReactCommon » TurboModule.cpp
› Compiling react-native Pods/ReactCommon » TurboCxxModule.cpp
› Packaging react-native Pods/glog » libglog.a
› Compiling react-native Pods/ReactCommon » ReactCommon-dummy.m
› Compiling react-native Pods/ReactCommon » RCTTurboModuleManager.mm
› Compiling react-native Pods/ReactCommon » RCTTurboModule.mm
› Packaging react-native Pods/React-perflogger » libReact-perflogger.a
› Packaging react-native Pods/Yoga » libYoga.a
› Compiling react-native Pods/React-jsinspector » React-jsinspector-dummy.m
› Compiling react-native Pods/React-jsi » jsilib-windows.cpp
› Compiling react-native Pods/React-jsi » jsilib-posix.cpp
› Compiling react-native Pods/React-jsi » jsi.cpp
› Packaging react-native Pods/React-jsinspector » libReact-jsinspector.a
› Compiling react-native Pods/React-jsi » React-jsi-dummy.m
› Compiling react-native Pods/React-jsi » JSIDynamic.cpp
› Compiling react-native Pods/React-bridging » React-bridging-dummy.m
› Compiling react-native Pods/React-jsiexecutor » React-jsiexecutor-dummy.m
› Compiling react-native Pods/React-jsiexecutor » JSINativeModules.cpp
› Compiling react-native Pods/React-RCTText » RCTVirtualTextViewManager.m
› Compiling react-native Pods/React-cxxreact » ReactMarker.cpp
› Compiling react-native Pods/React-cxxreact » React-cxxreact-dummy.m
› Compiling react-native Pods/React-cxxreact » RAMBundleRegistry.cpp
› Compiling react-native Pods/React-cxxreact » NativeToJsBridge.cpp
› Compiling react-native Pods/React-cxxreact » ModuleRegistry.cpp
› Compiling react-native Pods/React-cxxreact » MethodCall.cpp
› Compiling react-native Pods/React-cxxreact » JSIndexedRAMBundle.cpp
› Compiling react-native Pods/React-cxxreact » JSExecutor.cpp
› Compiling react-native Pods/React-cxxreact » JSBundleType.cpp
› Compiling react-native Pods/React-cxxreact » JSBigString.cpp
› Compiling react-native Pods/React-cxxreact » Instance.cpp
› Compiling react-native Pods/React-RCTText » RCTVirtualTextShadowView.m
› Compiling react-native Pods/React-RCTText » RCTUITextView.m
› Compiling react-native Pods/React-RCTText » RCTUITextField.m
› Compiling react-native Pods/React-RCTText » RCTTextViewManager.m
› Compiling react-native Pods/React-RCTText » RCTTextView.m
› Compiling react-native Pods/React-RCTText » RCTTextShadowView.m
› Compiling react-native Pods/React-RCTText » RCTTextSelection.m
› Compiling react-native Pods/React-RCTText » RCTTextAttributes.m
› Compiling react-native Pods/React-RCTText » RCTSinglelineTextInputViewManager.m
› Compiling react-native Pods/React-RCTText » RCTSinglelineTextInputView.m
› Compiling react-native Pods/React-RCTText » RCTRawTextViewManager.m
› Compiling react-native Pods/React-RCTText » RCTRawTextShadowView.m
› Compiling react-native Pods/React-RCTText » RCTMultilineTextInputViewManager.m
› Compiling react-native Pods/React-RCTText » RCTMultilineTextInputView.m
› Compiling react-native Pods/React-RCTText » RCTInputAccessoryViewManager.m
› Compiling react-native Pods/React-RCTText » RCTInputAccessoryViewContent.m
› Compiling react-native Pods/React-RCTText » RCTInputAccessoryView.m
› Compiling react-native Pods/React-RCTText » RCTInputAccessoryShadowView.m
› Compiling react-native Pods/React-RCTText » RCTConvert+Text.m
› Compiling react-native Pods/React-RCTText » RCTBaseTextViewManager.m
› Compiling react-native Pods/React-RCTText » RCTBaseTextShadowView.m
› Compiling react-native Pods/React-RCTText » RCTBaseTextInputViewManager.m
› Compiling react-native Pods/React-RCTText » RCTBaseTextInputView.m
› Compiling react-native Pods/React-RCTText » RCTBaseTextInputShadowView.m
› Compiling react-native Pods/React-RCTText » RCTBackedTextInputDelegateAdapter.m
› Compiling react-native Pods/RCTTypeSafety » RCTConvertHelpers.mm
› Compiling react-native Pods/React-Core » UIView+React.m
› Compiling react-native Pods/React-Core » React-Core-dummy.m
› Compiling react-native Pods/React-Core » RCTWrapperViewController.m
› Compiling react-native Pods/React-Core » RCTWeakProxy.m
› Compiling react-native Pods/React-Core » RCTViewUtils.m
› Compiling react-native Pods/React-Core » RCTViewRegistry.m
› Compiling react-native Pods/React-Core » RCTViewManager.m
› Compiling react-native Pods/React-Core » RCTView.m
› Compiling react-native Pods/React-Core » RCTVersion.m
› Compiling react-native Pods/React-Core » RCTUtilsUIOverride.m
› Compiling react-native Pods/React-Core » RCTUtils.m
› Compiling react-native Pods/React-Core » RCTUIUtils.m
› Compiling react-native Pods/React-Core » RCTUIManagerUtils.m
› Compiling react-native Pods/React-Core » RCTUIManagerObserverCoordinator.mm
› Compiling react-native Pods/React-Core » RCTUIManager.m
› Compiling react-native Pods/React-Core » RCTTouchHandler.m
› Compiling react-native Pods/React-Core » RCTTouchEvent.m
› Compiling react-native Pods/React-Core » RCTSwitchManager.m
› Compiling react-native Pods/React-Core » RCTSwitch.m
› Compiling react-native Pods/React-Core » RCTSurfaceView.mm
› Compiling react-native Pods/React-Core » RCTSurfaceStage.m
› Compiling react-native Pods/React-Core » RCTSurfaceSizeMeasureMode.mm
› Compiling react-native Pods/React-Core » RCTSurfaceRootView.mm
› Compiling react-native Pods/React-Core » RCTSurfaceRootShadowView.m
› Compiling react-native Pods/React-Core » RCTSurfacePresenterStub.m
› Compiling react-native Pods/React-Core » RCTSurfaceHostingView.mm
› Compiling react-native Pods/React-Core » RCTSurfaceHostingProxyRootView.mm
› Compiling react-native Pods/React-Core » RCTSurface.mm
› Compiling react-native Pods/React-Core » RCTSliderManager.m
› Compiling react-native Pods/React-Core » RCTSlider.m
› Compiling react-native Pods/React-Core » RCTShadowView.m
› Compiling react-native Pods/React-Core » RCTShadowView+Layout.m
› Compiling react-native Pods/React-Core » RCTShadowView+Internal.m
› Compiling react-native Pods/React-Core » RCTSegmentedControlManager.m
› Compiling react-native Pods/React-Core » RCTSegmentedControl.m
› Compiling react-native Pods/React-Core » RCTScrollViewManager.m
› Compiling react-native Pods/React-Core » RCTScrollView.m
› Compiling react-native Pods/React-Core » RCTScrollEvent.m
› Compiling react-native Pods/React-Core » RCTScrollContentViewManager.m
› Compiling react-native Pods/React-Core » RCTScrollContentView.m
› Compiling react-native Pods/React-Core » RCTScrollContentShadowView.m
› Compiling react-native Pods/React-Core » RCTSafeAreaViewManager.m
› Compiling react-native Pods/React-Core » RCTSafeAreaViewLocalData.m
› Compiling react-native Pods/React-Core » RCTSafeAreaView.m
› Compiling react-native Pods/React-Core » RCTSafeAreaShadowView.m
› Compiling react-native Pods/React-Core » RCTSRWebSocket.m
› Compiling react-native Pods/React-Core » RCTRootView.m
› Compiling react-native Pods/React-Core » RCTRootShadowView.m
› Compiling react-native Pods/React-Core » RCTRootContentView.m
› Compiling react-native Pods/React-Core » RCTReloadCommand.m
› Compiling react-native Pods/React-Core » RCTRefreshControlManager.m
› Compiling react-native Pods/React-Core » RCTRefreshControl.m
› Compiling react-native Pods/React-Core » RCTRedBoxSetEnabled.m
› Compiling react-native Pods/React-Core » RCTRedBoxExtraDataViewController.m
› Compiling react-native Pods/React-Core » RCTReconnectingWebSocket.m
› Compiling react-native Pods/React-Core » RCTProgressViewManager.m
› Compiling react-native Pods/React-Core » RCTProfile.m
› Compiling react-native Pods/React-Core » RCTPerformanceLoggerLabels.m
› Compiling react-native Pods/React-Core » RCTPerformanceLogger.m
› Compiling react-native Pods/React-Core » RCTParserUtils.m
› Compiling react-native Pods/React-Core » RCTPackagerConnection.mm
› Compiling react-native Pods/React-Core » RCTPackagerClient.m
› Compiling react-native Pods/React-Core » RCTObjcExecutor.mm
› Compiling react-native Pods/React-Core » RCTNativeModule.mm
› Compiling react-native Pods/React-Core » RCTMultipartStreamReader.m
› Compiling react-native Pods/React-Core » RCTMultipartDataTask.m
› Compiling react-native Pods/React-Core » RCTModuleRegistry.m
› Compiling react-native Pods/React-Core » RCTModuleMethod.mm
› Compiling react-native Pods/React-Core » RCTModuleData.mm
› Compiling react-native Pods/React-Core » RCTModalManager.m
› Compiling react-native Pods/React-Core » RCTModalHostViewManager.m
› Compiling react-native Pods/React-Core » RCTModalHostViewController.m
› Compiling react-native Pods/React-Core » RCTModalHostView.m
› Compiling react-native Pods/React-Core » RCTMessageThread.mm
› Compiling react-native Pods/React-Core » RCTMaskedViewManager.m
› Compiling react-native Pods/React-Core » RCTMaskedView.m
› Compiling react-native Pods/React-Core » RCTManagedPointer.mm
› Compiling react-native Pods/React-Core » RCTLog.mm
› Compiling react-native Pods/React-Core » RCTLayoutAnimationGroup.m
› Compiling react-native Pods/React-Core » RCTLayoutAnimation.m
› Compiling react-native Pods/React-Core » RCTLayout.m
› Compiling react-native Pods/React-Core » RCTKeyCommands.m
› Compiling react-native Pods/React-Core » RCTJavaScriptLoader.mm
› Compiling react-native Pods/React-Core » RCTJSThread.m
› Compiling react-native Pods/React-Core » RCTJSStackFrame.m
› Compiling react-native Pods/React-Core » RCTJSIExecutorRuntimeInstaller.mm
› Compiling react-native Pods/React-Core » RCTInspectorPackagerConnection.m
› Compiling react-native Pods/React-Core » RCTInspectorDevServerHelper.mm
› Compiling react-native Pods/React-Core » RCTInspector.mm
› Compiling react-native Pods/React-Core » RCTImageSource.m
› Compiling react-native Pods/React-Core » RCTI18nUtil.m
› Compiling react-native Pods/React-Core » RCTFrameUpdate.m
› Compiling react-native Pods/React-Core » RCTFont.mm
› Compiling react-native Pods/React-Core » RCTFollyConvert.mm
› Compiling react-native Pods/React-Core » RCTEventEmitter.m
› Compiling react-native Pods/React-Core » RCTEventDispatcher.m
› Compiling react-native Pods/React-Core » RCTErrorInfo.m
› Compiling react-native Pods/React-Core » RCTDisplayLink.m
› Compiling react-native Pods/React-Core » RCTDevLoadingViewSetEnabled.m
› Compiling react-native Pods/React-Core » RCTDefaultCxxLogFunction.mm
› Compiling react-native Pods/React-Core » RCTDatePickerManager.m
› Compiling react-native Pods/React-Core » RCTDatePicker.m
› Compiling react-native Pods/React-Core » RCTCxxUtils.mm
› Compiling react-native Pods/React-Core » RCTCxxModule.mm
› Compiling react-native Pods/React-Core » RCTCxxMethod.mm
› Compiling react-native Pods/React-Core » RCTCxxConvert.m
› Compiling react-native Pods/React-Core » RCTCxxBridge.mm
› Compiling react-native Pods/React-Core » RCTConvert.m
› Compiling react-native Pods/React-Core » RCTConvert+Transform.m
› Compiling react-native Pods/React-Core » RCTConvert+CoreLocation.m
› Compiling react-native Pods/React-Core » RCTConstants.m
› Compiling react-native Pods/React-Core » RCTComponentEvent.m
› Compiling react-native Pods/React-Core » RCTComponentData.m
› Compiling react-native Pods/React-Core » RCTCallableJSModules.m
› Compiling react-native Pods/React-Core » RCTBundleURLProvider.mm
› Compiling react-native Pods/React-Core » RCTBundleManager.m
› Compiling react-native Pods/React-Core » RCTBridgeModuleDecorator.m
› Compiling react-native Pods/React-Core » RCTBridge.m
› Compiling react-native Pods/React-Core » RCTBorderDrawing.m
› Compiling react-native Pods/React-Core » RCTAssert.m
› Compiling react-native Pods/React-Core » RCTAppSetupUtils.mm
› Compiling react-native Pods/React-Core » RCTActivityIndicatorViewManager.m
› Compiling react-native Pods/React-Core » RCTActivityIndicatorView.m
› Compiling react-native Pods/React-Core » NSDataBigString.mm
› Compiling react-native Pods/RCTTypeSafety » RCTTypedModuleConstants.mm
› Compiling react-native Pods/RCTTypeSafety » RCTTypeSafety-dummy.m
› Packaging react-native Pods/React-logger » libReact-logger.a
› Compiling react-native Pods/RCT-Folly » json_pointer.cpp
› Compiling react-native Pods/RCT-Folly » json.cpp
› Compiling react-native Pods/RCT-Folly » dynamic.cpp
› Compiling react-native Pods/RCT-Folly » UniqueInstance.cpp
› Compiling react-native Pods/RCT-Folly » Unicode.cpp
› Compiling react-native Pods/RCT-Folly » ToAscii.cpp
› Compiling react-native Pods/RCT-Folly » ThreadId.cpp
› Compiling react-native Pods/RCT-Folly » SysUio.cpp
› Compiling react-native Pods/RCT-Folly » String.cpp
› Compiling react-native Pods/RCT-Folly » SpookyHashV2.cpp
› Compiling react-native Pods/RCT-Folly » ScopeGuard.cpp
› Compiling react-native Pods/RCT-Folly » SafeAssert.cpp
› Compiling react-native Pods/RCT-Folly » RCT-Folly-dummy.m
› Compiling react-native Pods/RCT-Folly » NetOps.cpp
› Compiling react-native Pods/RCT-Folly » MallocImpl.cpp
› Compiling react-native Pods/RCT-Folly » Format.cpp
› Compiling react-native Pods/RCT-Folly » FileUtil.cpp
› Compiling react-native Pods/RCT-Folly » F14Table.cpp
› Compiling react-native Pods/RCT-Folly » Exception.cpp
› Compiling react-native Pods/RCT-Folly » Demangle.cpp
› Compiling react-native Pods/RCT-Folly » Conv.cpp
› Compiling react-native Pods/RCT-Folly » CString.cpp
› Compiling @shopify/flash-list Pods/RNFlashList » AutoLayoutViewManager.m
› Packaging react-native Pods/RCT-Folly » libRCT-Folly.a
› Packaging react-native Pods/React-jsi » libReact-jsi.a
› Copying   react-native React-Core/AccessibilityResources.bundle/en.lproj ➜ ../../node_modules/react-native/React/AccessibilityResources/en.lproj
› Preparing react-native Pods/React-Core-AccessibilityResources » ResourceBundle-AccessibilityResources-React-Core-Info.plist
› Packaging react-native Pods/React-bridging » libReact-bridging.a
› Packaging react-native Pods/React-cxxreact » libReact-cxxreact.a
› Packaging react-native Pods/React-jsiexecutor » libReact-jsiexecutor.a
› Compiling @shopify/flash-list Pods/RNFlashList » RNFlashList-dummy.m
› Compiling @shopify/flash-list Pods/RNFlashList » CellContainerManager.m
› Packaging react-native Pods/React-Core » libReact-Core.a
› Packaging react-native Pods/React-RCTText » libReact-RCTText.a
› Packaging @shopify/flash-list Pods/RNFlashList » libRNFlashList.a
› Packaging react-native Pods/RCTTypeSafety » libRCTTypeSafety.a
› Packaging react-native Pods/ReactCommon » libReactCommon.a
› Executing react-native Pods/FBReactNativeSpec » [CP-User] Generate Specs
› Compiling @acme/expo Pods/React-Codegen » FBReactNativeSpec-generated.mm
› Compiling react-native Pods/React-RCTVibration » RCTVibration.mm
› Compiling react-native Pods/React-RCTNetwork » RCTDataRequestHandler.mm
› Compiling react-native Pods/React-RCTSettings » RCTSettingsManager.mm
› Compiling react-native Pods/React-RCTLinking » RCTLinkingManager.mm
› Compiling react-native Pods/React-RCTAnimation » RCTAdditionAnimatedNode.m
› Compiling react-native Pods/React-RCTImage » RCTAnimatedImage.m
› Compiling react-native Pods/React-RCTBlob » RCTBlobCollector.mm
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » react-native-safe-area-context-dummy.m
› Compiling react-native Pods/React-CoreModules » CoreModulesPlugins.mm
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaViewMode.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaViewManager.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaViewLocalData.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaViewEdges.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaView.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaUtils.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaShadowView.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaProviderManager.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaProvider.m
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaContext.mm
› Compiling react-native Pods/React-RCTVibration » RCTVibrationPlugins.mm
› Compiling react-native Pods/React-RCTVibration » React-RCTVibration-dummy.m
› Compiling react-native Pods/React-RCTSettings » React-RCTSettings-dummy.m
› Compiling react-native Pods/React-RCTSettings » RCTSettingsPlugins.mm
› Compiling react-native Pods/React-RCTNetwork » React-RCTNetwork-dummy.m
› Compiling react-native Pods/React-RCTNetwork » RCTNetworking.mm
› Compiling react-native Pods/React-RCTNetwork » RCTNetworkTask.mm
› Compiling react-native Pods/React-RCTNetwork » RCTNetworkPlugins.mm
› Compiling react-native Pods/React-RCTNetwork » RCTHTTPRequestHandler.mm
› Compiling react-native Pods/React-RCTNetwork » RCTFileRequestHandler.mm
› Compiling react-native Pods/React-RCTLinking » React-RCTLinking-dummy.m
› Compiling react-native Pods/React-RCTLinking » RCTLinkingPlugins.mm
› Compiling react-native Pods/React-RCTBlob » React-RCTBlob-dummy.m
› Compiling react-native Pods/React-RCTImage » React-RCTImage-dummy.m
› Compiling react-native Pods/React-RCTImage » RCTUIImageViewAnimated.m
› Compiling react-native Pods/React-RCTImage » RCTResizeMode.m
› Compiling react-native Pods/React-RCTImage » RCTLocalAssetImageLoader.mm
› Compiling react-native Pods/React-RCTImage » RCTImageViewManager.mm
› Compiling react-native Pods/React-RCTImage » RCTImageView.mm
› Compiling react-native Pods/React-RCTImage » RCTImageUtils.m
› Compiling react-native Pods/React-RCTImage » RCTImageURLLoaderWithAttribution.mm
› Compiling react-native Pods/React-RCTImage » RCTImageStoreManager.mm
› Compiling react-native Pods/React-RCTImage » RCTImageShadowView.m
› Compiling react-native Pods/React-RCTImage » RCTImagePlugins.mm
› Compiling react-native Pods/React-RCTImage » RCTImageLoader.mm
› Compiling react-native Pods/React-RCTImage » RCTImageEditingManager.mm
› Compiling react-native Pods/React-RCTImage » RCTImageCache.m
› Compiling react-native Pods/React-RCTImage » RCTImageBlurUtils.m
› Compiling react-native Pods/React-RCTImage » RCTGIFImageDecoder.mm
› Compiling react-native Pods/React-RCTImage » RCTDisplayWeakRefreshable.m
› Compiling react-native Pods/React-RCTBlob » RCTFileReaderModule.mm
› Compiling react-native Pods/React-RCTBlob » RCTBlobPlugins.mm
› Compiling react-native Pods/React-RCTBlob » RCTBlobManager.mm
› Compiling react-native Pods/React-RCTAnimation » React-RCTAnimation-dummy.m
› Compiling react-native Pods/React-RCTAnimation » RCTValueAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTTransformAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTTrackingAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTSubtractionAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTStyleAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTSpringAnimation.m
› Compiling react-native Pods/React-RCTAnimation » RCTPropsAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTNativeAnimatedTurboModule.mm
› Compiling react-native Pods/React-RCTAnimation » RCTNativeAnimatedNodesManager.m
› Compiling react-native Pods/React-RCTAnimation » RCTNativeAnimatedModule.mm
› Compiling react-native Pods/React-RCTAnimation » RCTMultiplicationAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTModuloAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTInterpolationAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTFrameAnimation.m
› Compiling react-native Pods/React-RCTAnimation » RCTEventAnimation.m
› Compiling react-native Pods/React-RCTAnimation » RCTDivisionAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTDiffClampAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTDecayAnimation.m
› Compiling react-native Pods/React-RCTAnimation » RCTColorAnimatedNode.m
› Compiling react-native Pods/React-RCTAnimation » RCTAnimationUtils.m
› Compiling react-native Pods/React-RCTAnimation » RCTAnimationPlugins.mm
› Compiling react-native Pods/React-RCTAnimation » RCTAnimatedNode.m
› Compiling react-native Pods/React-CoreModules » React-CoreModules-dummy.m
› Compiling react-native Pods/React-CoreModules » RCTWebSocketModule.mm
› Compiling react-native Pods/React-CoreModules » RCTWebSocketExecutor.mm
› Compiling react-native Pods/React-CoreModules » RCTTiming.mm
› Compiling react-native Pods/React-CoreModules » RCTStatusBarManager.mm
› Compiling react-native Pods/React-CoreModules » RCTSourceCode.mm
› Compiling react-native Pods/React-CoreModules » RCTRedBox.mm
› Compiling react-native Pods/React-CoreModules » RCTPlatform.mm
› Compiling react-native Pods/React-CoreModules » RCTPerfMonitor.mm
› Compiling react-native Pods/React-CoreModules » RCTLogBoxView.mm
› Compiling react-native Pods/React-CoreModules » RCTLogBox.mm
› Compiling react-native Pods/React-CoreModules » RCTKeyboardObserver.mm
› Compiling react-native Pods/React-CoreModules » RCTI18nManager.mm
› Compiling react-native Pods/React-CoreModules » RCTFPSGraph.m
› Compiling react-native Pods/React-CoreModules » RCTExceptionsManager.mm
› Compiling react-native Pods/React-CoreModules » RCTEventDispatcher.mm
› Compiling react-native Pods/React-CoreModules » RCTDeviceInfo.mm
› Compiling react-native Pods/React-CoreModules » RCTDevSplitBundleLoader.mm
› Compiling react-native Pods/React-CoreModules » RCTDevSettings.mm
› Compiling react-native Pods/React-CoreModules » RCTDevMenu.mm
› Compiling react-native Pods/React-CoreModules » RCTDevLoadingView.mm
› Compiling react-native Pods/React-CoreModules » RCTClipboard.mm
› Compiling react-native Pods/React-CoreModules » RCTAsyncLocalStorage.mm
› Compiling react-native Pods/React-CoreModules » RCTAppearance.mm
› Compiling react-native Pods/React-CoreModules » RCTAppState.mm
› Compiling react-native Pods/React-CoreModules » RCTAlertManager.mm
› Compiling react-native Pods/React-CoreModules » RCTAlertController.m
› Compiling react-native Pods/React-CoreModules » RCTActionSheetManager.mm
› Compiling react-native Pods/React-CoreModules » RCTAccessibilityManager.mm
› Compiling @acme/expo Pods/React-Codegen » React-Codegen-dummy.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXAppDefines.m
› Packaging @acme/expo Pods/React-Codegen » libReact-Codegen.a
› Packaging react-native Pods/React-RCTVibration » libReact-RCTVibration.a
› Packaging react-native Pods/React-RCTSettings » libReact-RCTSettings.a
› Packaging react-native Pods/React-RCTNetwork » libReact-RCTNetwork.a
› Packaging react-native Pods/React-RCTLinking » libReact-RCTLinking.a
› Packaging react-native Pods/React-RCTAnimation » libReact-RCTAnimation.a
› Packaging react-native Pods/React-RCTImage » libReact-RCTImage.a
› Packaging react-native Pods/React-RCTBlob » libReact-RCTBlob.a
› Packaging react-native-safe-area-context Pods/react-native-safe-area-context » libreact-native-safe-area-context.a
› Packaging react-native Pods/React-CoreModules » libReact-CoreModules.a
› Compiling expo-modules-core Pods/ExpoModulesCore » TypedArray.cpp
› Compiling expo-modules-core Pods/ExpoModulesCore » ExpoModulesHostObject.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXViewManagerAdapterClassesRegistry.m
› Compiling expo-modules-core Pods/ExpoModulesCore » ExpoBridgeModule.m
› Compiling expo-modules-core Pods/ExpoModulesCore » ExpoModulesCore-dummy.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXViewManagerAdapter.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXUtilities.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXViewManager.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXSingletonModule.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXReactNativeEventEmitter.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXReactNativeUserNotificationCenterProxy.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXReactNativeAdapter.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXReactLogHandler.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXReactFontManager.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXReactDelegateWrapper.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXReactCompatibleHelpers.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXRCTBridgeDelegateInterceptor.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXPermissionsService.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXPermissionsMethodsDelegate.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXNativeModulesProxy.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXModuleRegistryProvider.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXModuleRegistryHolderReactModule.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXModuleRegistryAdapter.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXModuleRegistry.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXLogManager.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXLegacyAppDelegateWrapper.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptWeakObject.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptValue.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptTypedArray.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptRuntime.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptObject.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIUtils.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIInstaller.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIConversions.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXExportedModule.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXErrorCodes.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXAppDelegatesLoader.m
› Compiling expo-modules-core Pods/ExpoModulesCore » EXAppDelegateWrapper.m
› Packaging expo-modules-core Pods/ExpoModulesCore » libExpoModulesCore.a
› Executing expo-modules-core Pods/ExpoModulesCore » Copy generated compatibility header
› Compiling expo Pods/Expo » EXAppDefinesLoader.m
› Compiling expo-font Pods/EXFont » EXFont.m
› Compiling expo-application Pods/EXApplication » EXApplication.m
› Compiling expo-application Pods/EXApplication » EXApplication-dummy.m
› Compiling expo-keep-awake Pods/ExpoKeepAwake » KeepAwakeModule.swift
› Preparing expo-constants Pods/EXConstants-EXConstants » ResourceBundle-EXConstants-EXConstants-Info.plist
› Executing expo-splash-screen Pods/EXSplashScreen » [CP] Copy XCFrameworks
› Executing expo-file-system Pods/EXFileSystem » [CP] Copy XCFrameworks
› Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest
› Compiling expo-application Pods/EXApplication » EXProvisioningProfile.m
› Compiling expo-font Pods/EXFont » EXFontManager.m
› Compiling expo-font Pods/EXFont » EXFontLoaderProcessor.m
› Compiling expo-font Pods/EXFont » EXFontScalersManager.m
› Compiling expo-font Pods/EXFont » EXFontLoader.m
› Compiling expo-font Pods/EXFont » EXFontScaler.m
› Compiling expo-font Pods/EXFont » EXFont-dummy.m
› Compiling expo-constants Pods/EXConstants » EXConstants.m
› Packaging expo-application Pods/EXApplication » libEXApplication.a
› Compiling expo-constants Pods/EXConstants » EXConstants-dummy.m
› Packaging expo-font Pods/EXFont » libEXFont.a
› Compiling expo Pods/Expo » Expo-dummy.m
› Compiling expo-constants Pods/EXConstants » EXConstantsService.m
› Compiling expo-constants Pods/EXConstants » EXConstantsInstallationIdProvider.m
› Packaging expo Pods/Expo » libExpo.a
› Packaging expo-constants Pods/EXConstants » libEXConstants.a
› Compiling expo-keep-awake Pods/ExpoKeepAwake » ExpoKeepAwake-dummy.m
› Packaging expo-keep-awake Pods/ExpoKeepAwake » libExpoKeepAwake.a
› Executing expo-keep-awake Pods/ExpoKeepAwake » Copy generated compatibility header
› Executing @shopify/flash-list Pods/RNFlashList » Copy generated compatibility header
    Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the expo editor. (in target 'expo' from project 'expo')
› Compiling Pods/Pods-expo » Pods-expo-dummy.m
› Packaging Pods/Pods-expo » libPods-expo.a
› Executing expo » [CP] Check Pods Manifest.lock
› Executing expo » Start Packager on http://localhost:8081
› Compiling expo » ExpoModulesProvider.swift
› Compiling expo » noop-file.swift
› Compiling expo » main.m
› Compiling expo » expo_vers.c
› Compiling expo » AppDelegate.mm
› Linking   expo » expo
⚠️  ld: duplicate method '+moduleName' in
┌─[category]: ExpoBridgeModule-29f0c1a27a7bd5530b831d82e9038ac3.o ExpoModulesCore/libExpoModulesCore.a
└─[class]: ExpoBridgeModule-84674e26e826db07ace0cbde5ca591d6.o ExpoModulesCore/libExpoModulesCore.a

› Compiling expo » SplashScreen.storyboard
› Preparing expo » Info.plist
› Copying   ios/expo/Supporting/Expo.plist ➜ ./Expo.plist
› Generating debug expo » expo.app.dSYM
› Executing expo » Bundle React Native code and images
› Executing expo » [CP] Copy Pods Resources
› Signing   expo » expo.app
› Build Succeeded

› 0 error(s), and 2 warning(s)

Starting Metro Bundler
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▄▄ ▀▄▄ █ ██ █▄██▄██▀█ ▄▄▄▄▄ █
█ █   █ █▀▄  ██ ▀▄▀ ██ █▀█▀█▀ █ █   █ █
█ █▄▄▄█ █▄▀ █▄  ▄▀▄▀▄█▄ ▄ ▄▀█▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄█ ▀▄█▄█ ▀ █▄█▄█ █ █▄▄▄▄▄▄▄█
█▄ ▀▀█▄▄▄█▄ █▄█ ▄█   ▀█▄ ▄▄ ▀█▀██  ████
█▄ ▀▀▀█▄█▄▀▀ ▄█▀▀▀▄▀▀█▄▄▀ █ ▄ ██   ▄  █
█▄▀▀▄▀▄▄▀▄▀▀█▀  █▄█▄ ██▀ █▀█  ▄▄ █ ▀▄▄█
█▄▄▀▄▀█▄▄█  █▀  ▄ █▄█ ▄▀██▄  █ ██▀▀ ▄▄█
█ ██  ▄▄  ███▄█▄ ▄   ▄██▀█▄   █▄ ▄  ▄██
█▀▀█ ▄▄▄█ ▄ ▀▄▄ ▄▄█▀▄█▄▀ █▄█▄▀▀█▄  █  █
█▀███▀▄▄▀▀▄▀▄▀▀█▀ ▄▄▀ ██ ▀ ▀ █▄▄  █▄▄██
█ ██ █▄▄ ▄▄ █▀ ▄▄██▄▀▀█▀▀██ ▄▀   █▀█ ▄█
█▀  █ ▄▄▄██ ▄▄▄█ ██▄▄ ▄█▀ ██  ▀▄ █ ▀███
█ █████▄█▄▄▄ ▄██▄▀█▄▀▀▄██▄▄█▄▄█▀▀▄▀▀ ▄█
█▄█▄█▄█▄▄▀▄▄▄▀▀▀▀▄ ▄▀▄██▀█ ▄█ ▄▄▄   █▄█
█ ▄▄▄▄▄ █ ▄▄▄▀▀█▄█▄ ▄▀▄▀ ▄▄██ █▄█ ▀█▀▄█
█ █   █ ██▀██▄█ ▄█▄ ▀▀██ ▄   ▄  ▄▄▀ ▀ █
█ █▄▄▄█ █▀█▄ ▄█▀ ▄██▀▀█████▀█ ▄▀▀▀▀█▄ █
█▄▄▄▄▄▄▄█▄▄▄██▄▄▄██▄▄▄▄█▄▄███▄▄▄▄▄███▄█

› Metro waiting on
com.anonymous.expo://expo-development-client/?url=http%3A%2F%2F192.168.1.118%3A8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

› Installing on iPhone 13 Pro Max
› Opening on iPhone 13 Pro Max (com.anonymous.expo)
› Opening com.anonymous.expo://expo-development-client/?url=http%3A%2F%2F192.168.1.118%3A8081 on iPhone 13 Pro Max

› Logs for your project will appear below. Press Ctrl+C to exit.
Error: Unable to resolve module ./index from /Users/nelson/test/apps/expo/.:

None of these files exist:
  * index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  * index/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
    at ModuleResolver.resolveDependency (/Users/nelson/test/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Users/nelson/test/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/nelson/test/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/Users/nelson/test/node_modules/metro/src/Server.js:1137:12)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/nelson/test/node_modules/metro/src/Server.js:464:37)
    at async Server._processRequest (/Users/nelson/test/node_modules/metro/src/Server.js:420:9)


```

**Comment by nrowley** [comment]
is this a metro config error?

**Comment by nrowley** [comment]
i've created a pr for this #32

**Comment by nrowley** [comment]
resolved https://github.com/t3-oss/create-t3-turbo/pull/32

**Comment by alrightsure** [comment]
This is still happening with a fresh clone and running "expo start"
