### ISSUE TITLE
bug: Use process(css).then(cb) to work with async plugins

### ISSUE THREAD

**Issue by wardch** [t3-oss/create-t3-turbo#436]
### Provide environment information

```

  System:
    OS: macOS 13.3.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 720.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm

```

### Describe the bug

When the steps are followed in the quick start, all goes well until running `pnpm dev`. At this point there is an error which reads: 

```
@acme/expo:dev: iOS Bundling failed 2805ms
@acme/expo:dev: error: src/app/post/[id].tsx: /Users/charlieward/Desktop/smart-chef-cli/apps/expo/src/app/post/[id].tsx: Use process(css).then(cb) to work with async plugins
```

### Link to reproduction

Screenshot attached

### To reproduce

Follow each steps of the quick start with node version 18.16.1. 

### Additional information

![Screenshot 2023-07-18 at 12 03 08 PM](https://github.com/t3-oss/create-t3-turbo/assets/10323308/15185b58-55dd-47ef-b6f2-986fe1d54509)

**Comment by juliusmarminge** [comment]
use tailwind@3.3.2 - will get this fixed. there are 2 open PRs for expo 49 and will get this fixed at the same tiem

**Comment by Kylar13** [comment]
I downgraded to tailwind@3.3.2 and I'm still getting this.
![image](https://github.com/t3-oss/create-t3-turbo/assets/7138244/f80f6f9a-f230-4451-883b-af5dd688b806)

I only get it on android tho, iOS builds work fine.

**Comment by wardch** [comment]
I'm still getting the same error when I switch to tailwind 3.3.2. I updated the package.json files of the app, deleted my pnpm.lock file, ran pnpm i again, but still get the same error `Use process(css).then(cb) to work with async plugins `

 here's my package.json at the root: 

```json
{
  "name": "create-t3-turbo",
  "private": true,
  "engines": {
    "node": ">=v18.16.1"
  },
  "packageManager": "pnpm@8.6.7",
  "scripts": {
    "build": "turbo build",
    "clean": "git clean -xdf node_modules",
    "clean:workspaces": "turbo clean",
    "db:generate": "turbo db:generate",
    "db:push": "turbo db:push db:generate",
    "db:studio": "pnpm -F db dev",
    "dev": "turbo dev --parallel",
    "format": "prettier --write \"**/*.{js,cjs,mjs,ts,tsx,md,json}\" --ignore-path .gitignore",
    "lint": "turbo lint && manypkg check",
    "lint:fix": "turbo lint:fix && manypkg fix",
    "type-check": "turbo type-check"
  },
  "dependencies": {
    "@ianvs/prettier-plugin-sort-imports": "^4.1.0",
    "@manypkg/cli": "^0.21.0",
    "prettier": "^3.0.0",
    "prettier-plugin-tailwindcss": "^0.4.1",
    "turbo": "^1.10.7",
    "typescript": "^5.1.6"
  }
}

```

Then in the package json in app/expo and app/nextjs I changed the tailwind dev depdendency to be: `"tailwindcss": "^3.3.2"`

**Comment by juliusmarminge** [comment]
> Then in the package json in app/expo and app/nextjs I changed the tailwind dev depdendency to be: "tailwindcss": "^3.3.2"

That will still pull 3.3.3. Set the version to be exact:

`"tailwindcss": "3.3.2"`

**Comment by Kylar13** [comment]
> > Then in the package json in app/expo and app/nextjs I changed the tailwind dev depdendency to be: "tailwindcss": "^3.3.2"
> 
> That will still pull 3.3.3. Set the version to be exact:
> 
> `"tailwindcss": "3.3.2"`

I do realise you were not talking to me, but I did make sure in the lockfiles that version 3.3.2 was installed in all instances of tailwindcss + it only seems to happen on android builds for me.

Do you have any idea what might be causing it? By the looks of the error it's still related to postcss so it's still a tailwind issue, but I'm not sure what else to try

**Comment by juliusmarminge** [comment]
> Do you have any idea what might be causing it? By the looks of the error it's still related to postcss so it's still a tailwind issue, but I'm not sure what else to try

Unfortunately no, I suggest posting in this issue and see if anyone knows what's up with android: https://github.com/postcss/postcss/issues/412

**Comment by iamkingrobert** [comment]
I use tailwind@3.3.2 and it fixed the problem.

**Comment by mog-rn** [comment]
> I use tailwind@3.3.2 and it fixed the problem.

This solution also works for me. I also came across the solution on this post [here.](https://stackoverflow.com/questions/76690321/typescript-error-use-processcss-thencb-to-work-with-async-plugins)

**Comment by juliusmarminge** [comment]
Closing as completed. If you still encounter this I suggest following the postcss issue

**Comment by WebDevJasim** [comment]
i was facing same issue last two days but this work for me : 
yarn add postcss@8.4.23 
yarn add --dev tailwindcss@3.3.2

**Comment by htran844** [comment]
in package.json file, change "tailwindcss": "^3.3.2", to "tailwindcss": "~3.3.2",

**Comment by bhawanjr** [comment]
> i was facing same issue last two days but this work for me : yarn add postcss@8.4.23 yarn add --dev tailwindcss@3.3.2

Thank you, it's work to me
