### ISSUE TITLE
bug(android): `main: expo-router/entry` is not resolved

### ISSUE THREAD

**Issue by jimsheen** [t3-oss/create-t3-turbo#741]
### Provide environment information

 System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 96.88 MB / 8.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.0 - /opt/homebrew/bin/npm

### Describe the bug

When attempting to run the Expo app in the Android emulator environment, specifically on the Pixel_7_API_UpsideDownCakePrivacySandbox, the module resolution fails with an error for expo-router/entry. This issue does not occur when running the Next.js project, which proceeds without any hitches.

```
Error: Unable to resolve module ./node_modules/expo-router/entry from <PROJECT_ROOT>/apps/expo/.: 

None of these files exist:
  * node_modules/expo-router/entry(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.css|.native.css|.css)
  * node_modules/expo-router/entry/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.css|.native.css|.css)
    at ModuleResolver.resolveDependency (<PROJECT_ROOT>/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (<PROJECT_ROOT>/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at <PROJECT_ROOT>/node_modules/metro/src/lib/transformHelpers.js:169:21
    at Server._resolveRelativePath (<PROJECT_ROOT>/node_modules/metro/src/Server.js:1045:12)
    at async Server.requestProcessor [as _processBundleRequest] (<PROJECT_ROOT>/node_modules/metro/src/Server.js:449:37)
    at async Server._processRequest (<PROJECT_ROOT>/node_modules/metro/src/Server.js:383:7)
```

### Link to reproduction

-

### To reproduce

Initialise the project using create-t3-turbo.
Install dependencies with pnpm i.
Push database changes with pnpm db:push.
Start the development server using pnpm dev.
After following these steps, the Next.js project runs correctly, while the Expo app does not, resulting in a resolution error for the expo-router/entry module when trying to launch from index.tsx.

Expected Behaviour:
The Expo app should resolve all modules correctly and launch without errors, similar to the Next.js project's behavior.

Actual Behavior:
The Expo app fails to resolve the expo-router/entry module and throws an error, preventing the app from running on the Android emulator.

### Additional information

This works fine with the iOS simulator

**Comment by juliusmarminge** [comment]
cc @byCedric - do you know if this is an issue on the Expo side? iOS works but android doesnt it seems like. Have had similar reports before

**Comment by DJanocha** [comment]
Has someone any suggestions on how to make make it work?
From what I understand, thanks to the '.npmrc' file, node_modules are hoisted, so everything that is not a part of monorepo is hoisted to root node_modules. Unfortunately expo tries to load 'expo-router' from '~apps/expo/node_modules' instead of '~/node_modules'.
If somebody knows which library should be downgraded/upgraded or whatever to make the app runnable in android emulator, please don't hesitate to share :)

**Comment by juliusmarminge** [comment]
You can create index.js and import expo router entry there, then point package.json:main to that

**Comment by DJanocha** [comment]
Works as expected. Thank you.
For those who are still not sure how to do it:
1. change the 'main' property inside of expo app package.json from
from: `  "main": "expo-router/entry",`
to: `  "main": "index.js",`
2. add needed `index.js` file to the root of the project. In my case I created `apps/expo/index.js` file alongside (not inside of) the `src` directory.
3. inside of the `index.js` file I added just 1 line:
```
import 'expo-router/entry'
```
4. save all files and restart the expo:android server

**Comment by juliusmarminge** [comment]
Someone should file this issue to Expo

**Comment by jeffrey-dot-li** [comment]
> Works as expected. Thank you. For those who are still not sure how to do it:
> 
>     1. change the 'main' property inside of expo app package.json from
>        from: `  "main": "expo-router/entry",`
>        to: `  "main": "index.js",`
> 
>     2. add needed `index.js` file next to the `package.json` file. In my case I created `apps/expo/index.js` file .
> 
>     3. inside of the `index.js` file I added just 1 line:
> 
> 
> ```
> import 'expo-router/entry'
> ```
> 
>     4. save all files and restart the expo:android server
> 
> 
> This should work as it did in my case.

Thank you so much. Was running into same issue with IOS emulator. This fixed it

**Comment by dingyuchen** [comment]
did the steps as above, but got a new error.
<img width="570" alt="image" src="https://github.com/t3-oss/create-t3-turbo/assets/9072299/b4ab05cb-646c-4004-8f07-65361c88475c">

This is for the IOS simulator

**Comment by kennethkeim** [comment]
[This](https://github.com/expo/expo/issues/21820) seems like the issue in expo, but the [solution there](https://github.com/expo/expo/issues/21820#issuecomment-1506079581) doesn't work for me (the referenced npmrc setting is already there and I deleted the lock files and node_modules and re-installed).

**Comment by joshsmith** [comment]
None of the solutions referenced so far have worked for me, but I upgraded to Expo SDK 50 and found that the problem went away. I can't tell if it's the change to `expo-router` v3 or the way that 50 now handles `node_modules`. This was the only fix I could find.

**Comment by juliusmarminge** [comment]
Resolved in sdk 50 which we just updated to in #795

**Comment by HarunKilic** [comment]
Weirdly, I am still experiencing this issue. Even with sdk 50.

**Comment by HarunKilic** [comment]
nvm, worked after cleaning xD

**Comment by HarunKilic** [comment]
Okay weird. Suddenly its not working again

**Comment by HarunKilic** [comment]
It does work with this method tho: https://github.com/t3-oss/create-t3-turbo/issues/741#issuecomment-1812454342
But not when "main" in package.json is set to "expo-router/entry"

**Comment by dBianchii** [comment]
This is still happening to me. I had to do the index.js trick explained by @DJanocha

**Comment by AryanJ-NYC** [comment]
Just as a data point, I too had this problem (only on Android) and it was resolved using the `index.js` trick.

```json
"dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.11",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.7",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.15",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.6",
    "expo-web-browser": "~13.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.2",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.2.45",
    "@types/react-native": "~0.73.0",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.1",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
```
